### ISSUE TITLE
Link to Python bindings for GMime

### ISSUE THREAD

**Issue by pabs3** [jstedfast/gmime#107]
Please add a link in the README.md to the Python Bindings for GMime maintained by @noyeitan:

https://github.com/noyeitan/pygmime

pygmime used to be maintained by @jkr, but their repository is now archived and read-only:

https://github.com/jkr/pygmime

**Comment by pabs3** [comment]
Actually, nevermind, I just noticed it doesn't support any recent version of GMime unfortunately.

**Comment by jstedfast** [comment]
Bummer.
