### ISSUE TITLE
broken links to developer documentation

### ISSUE THREAD

**Issue by pabs3** [jstedfast/gmime#108]
The developer documentation linked from the About section of the GMime GitHub sidebar, and from the Documentation section of the README.md has moved here:

https://developer-old.gnome.org/gmime/stable/

**Comment by jstedfast** [comment]
Thanks.

**Comment by jstedfast** [comment]
Fixed.

**Comment by pabs3** [comment]
Thanks.

BTW, putting this in the commit would have closed it automatically, listing the commit that closed it:

```
Fixes: https://github.com/jstedfast/gmime/issues/108
```

FTR, the README was fixed in commit efb2aa0.
