### ISSUE TITLE
autogen.sh has invalid shell syntax

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#109]
in bfa72b11943204a0955bb3a0a603f7c56ca97f1e `autogen.sh` adopted `$(srcdir)` instead of `$srcdir` -- but this isn't valid equivalent syntax in shell.  Maybe you meant `${srcdir}` instead?  `$(xxx)` executes a subshell running the program `xxx` and substitutes its output, while `${xxx}` expands an environment variable named `xxx`.

**Comment by dkg** [comment]
(the switch in that same commit from `which` to `command -v` is distinct from this variable substitution syntax mixup, and is probably ok, and worth keeping)

**Comment by jstedfast** [comment]
Thanks, this should be fixed now I think
