### ISSUE TITLE
The samples from README wont compile

### ISSUE THREAD

**Issue by emdete** [jstedfast/gmime#117]
It seems the samples in the README are outdated. First one i tried did not compile. I suggest to move the code into the sample directory, add links from the README and add its build to the test flow.

What do you think?

**Comment by jstedfast** [comment]
Which sample?

**Comment by emdete** [comment]
I had troubles with each of the samples from the README, even adding the init doesnt remove the warnings and i think learning-code should be warning free ;)

sure, i checked the `examples/` as well but those do not contain one that creates an email, adding attachment, encrypt, use autocrypt and alll the fine features gmime provides.

**Comment by jstedfast** [comment]
If you could paste your full program for each sample and the compile warnings you got, I'll fix them. I don't have a Linux machine anymore so I can't do it myself.

**Comment by jstedfast** [comment]
The only compile errors I've seen so far are GMimePart vs GMimeTextPart (GMimeTextPart subclasses GMimePart, so it's fine, but does present warnings). GMimeTextPart was added more recently (2 or 3 years ago?) to make setting/getting text simpler for the average user - before they would have to manipulate a GMimePart directly to get it.

**Comment by jstedfast** [comment]
Found/fixed a compile error for getting the mbox marker & offset from the parser.

**Comment by emdete** [comment]
I wrote a small script to compile all samples:

```
#!/usr/bin/env python3    
from subprocess import call    
s = None    
no = 0    
with open('../README') as r:    
    for line in r.readlines():    
        line = line.strip()    
        if line == '```c':    
            s = open(f'{no:02}.c', 'w')    
            print('#include <stdio.h>', file=s)    
            print('#include <stdlib.h>', file=s)    
            print('#include <string.h>', file=s)    
            print('#include <fcntl.h>', file=s)    
            print('#include <time.h>', file=s)    
            print('#include <glib.h>', file=s)    
            print('#include <glib/gstdio.h>', file=s)    
            print('', file=s)    
            print('#include <gmime/gmime.h>', file=s)    
            print('', file=s)    
            print('int main() {', file=s)    
            print('g_mime_init();', file=s)    
            print('g_mime_charset_map_init();', file=s)    
        elif s and line == '```':    
            print('g_mime_shutdown();', file=s)    
            print('return 0;', file=s)    
            print('}', file=s)    
            s.close()    
            retcode = call(f'gcc $(pkg-config --cflags gmime-3.0) -o {no:02} {no:02}.c $(pkg-config --libs gmime-3.0)', shell=True)    
            s = None    
            no += 1    
        elif s:    
            print(line, file=s) 
```

so it's easy to see the warnings & errors (for example `g_mime_parser_construct_message` is called with one instead of two args). Full log is https://mister-muffin.de/p/vmXN.c

**Comment by jstedfast** [comment]
They should all be fixed now, but you can't expect your script to produce clean builds for all of the samples because some of them call functions like `CreateMessage()` that is up to you to implement.

Also, don't call g_mime_charset_map_init() directly - let g_mime_init() call that.

**Comment by emdete** [comment]
Thank you!

How about putting a plain

```
GMimeMessage *message;
```

into the sample to make clear that this is needed and make the samples compile? The type safe G-cast-macros like GMIME_OBJECT could be added too. About the samples that need each other i need to think..

I think it would be cool if the samples compile to see if they still fit after changes. They could go into the test cycle. Outdated samples are a waste of time for newbies like myself ;)

i didnt know about the other init, the doc doesnt tell. Maybe that can be added as well?

**Comment by emdete** [comment]
i adapted the README.md a bit and changed the script. Everything compiles now (but probably cores). If you are interested let me knw, i would do a PR then.
