### ISSUE TITLE
Don’t call g_time_zone_new_offset() with offsets >24 hours

### ISSUE THREAD

**Issue by pwithnall** [jstedfast/gmime#120]
This is part of https://gitlab.gnome.org/GNOME/glib/-/issues/2620, which in turn came from Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007226.

[Calling `g_time_zone_new_offset()`](https://github.com/jstedfast/gmime/blob/0923bcd81253e3d3e9e33dd55f3133c7419340d4/gmime/gmime-utils.c#L488) with a large offset (>24h) will cause an assertion failure in GLib <2.72.0. There’s [a fix](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2554) for GLib 2.72.0, but older versions of GLib will still have this (or a different) assertion failure.

`g_time_zone_new_offset()` isn’t an ideal API, in that it has no way of reporting errors, and not all timezone offsets are valid. Currently there is no direct replacement.

You have several options, depending on what makes the most sense for how GMime handles timezones internally:
 * Validate the offset before calling `g_time_zone_new_offset()`. The downside is that I can’t say for certain that offsets <24h will be valid, as the validity depends on what’s defined in the system tzdb
 * Check the return value of `g_time_zone_new_offset()` to see if it’s the UTC timezone. If it is, and that wasn’t expected (i.e. the offset wasn’t 0), then creating the timezone failed.
 * Call `g_time_zone_new_identifier()` instead, [as `g_time_zone_new_offset()` does internally](https://gitlab.gnome.org/GNOME/glib/-/blob/7f0f87355b65f72be5e6351c66829c6df6dc6e4c/glib/gtimezone.c#L2050). It *can* report errors.

**Comment by jstedfast** [comment]
Thanks. I ended up using your g_time_zone_new_identifier() recommendation.

**Comment by jstedfast** [comment]
Can you let the person who originally filed the bug report that I will make a new release with the bug fix "soon" (next few days)? Thanks!

**Comment by frozencemetery** [comment]
It's me, and understood, thanks!

**Comment by jstedfast** [comment]
Released: https://github.com/jstedfast/gmime/releases/tag/3.2.10

**Comment by jstedfast** [comment]
Fuuuuuuuuuuu... new base64 decoder was broken.

Releasing 3.2.11. Gah!

**Comment by jstedfast** [comment]
https://github.com/jstedfast/gmime/releases/tag/3.2.11
