### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by mattst88** [jstedfast/gmime#125]
I'd like to close out https://bugs.gentoo.org/811963 which has been fixed upstream since the last release. Would you mind tagging a new minor release with that fix in it?

Thanks!

**Comment by jstedfast** [comment]
Sure, no problem. Let me go do that right now.

**Comment by jstedfast** [comment]
Released: https://github.com/jstedfast/gmime/releases/tag/3.2.12

**Comment by mattst88** [comment]
Thanks! \o/
