### ISSUE TITLE
internet_address_list_append_parse is a visible symbol, but not exposed via <gmime/internet-address.h>

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#128]
in 3.2.13, (in d0d4d6ce495cd819b8a4dfcf8b8286ad459dff13), `internet_address_list_append_parse` is introduced.  This is exposed by the gmime library as a visible symbol, but it is not described in the corresponding header file.

If this is intended to be visible externally, i think it should be in the header file.  If it's not intended to be visible externally, maybe it should be marked to not be exposed in the shared object?

**Comment by jstedfast** [comment]
Sorry about that. I was so focused on the internal API, I forgot that I started to make a public API wrapper for it.
