### ISSUE TITLE
g_mime_object_write_to_stream() with GMimeStreamFs does not work as before with GMime 3

### ISSUE THREAD

**Issue by gauteh** [jstedfast/gmime#13]
Hi,

I'm trying to port my code for sending messages through piping them to a stdin file descriptor to GMime 3. The following code seems to just produce empty messages, I am testing with piping into `tee file`:

```
      /* write message to sendmail */
      GMimeStream * stream = g_mime_stream_fs_new (stdin);
      g_mime_stream_fs_set_owner (GMIME_STREAM_FS(stream), true);
      g_mime_object_write_to_stream(GMIME_OBJECT(message), g_mime_format_options_get_default (), stream);
      g_mime_stream_flush (stream);
      g_object_unref (stream); // closes stdin

      /* wait for sendmail to finish */
      int status;
      pid_t wp = waitpid (pid, &status, 0);
```

If I use `file_new` with an actual file it works fine, `g_mime_object_to_ string()` also shows a nice message.

**Comment by gauteh** [comment]
If I revert af98de5b7e51a208da1bd99027b8b8f48427d3a3 it works.

**Comment by gauteh** [comment]
So the culprit is: https://github.com/jstedfast/gmime/blob/master/gmime/gmime-stream-fs.c#L202, `lseek` does not seem to work (or make any sense) for `stdin`.

**Comment by jstedfast** [comment]
You should be using GMimeStreamPipe for this - it's identical to GMimeStreamFs except it doesn't seek.

**Comment by gauteh** [comment]
Ok - thanks.

**Comment by jstedfast** [comment]
no problem!
