### ISSUE TITLE
gmime-format-options.h: bad <a>

### ISSUE THREAD

**Issue by jwilk** [jstedfast/gmime#131]
`gmime/gmime-format-options.h` says:

```
 * Content-Disposition parameter values is the method described in
 * <a href="https://tools.ietf.org/html/rfc2231">rfc2231</a>. However, it is common for
 * some older email clients to improperly encode using the method described in
 * <a href="https://tools.ietf.org/html/rfc2047">rfc2047</a> instead.
```

But the `<a href="…">` syntax doesn't seem to be understood by documentation generators.
In <https://developer-old.gnome.org/gmime/stable/gmime-GMimeFormatOptions.html#GMimeParamEncodingMethod>, this fragment shows up as:

> The MIME specifications specify that the proper method for encoding Content-Type and Content-Disposition parameter values is the method described in 
> &lt;a>rfc2231&lt;/a>. However, it is common for 
> some older email clients to improperly encode using the method described in 
> &lt;a>rfc2047&lt;/a> instead.

**Comment by jstedfast** [comment]
Ugh, thanks for the heads-up on that. I might just kill the href links.

**Comment by jwilk** [comment]
According to <https://wiki.gnome.org/DocumentationProject/GtkDoc#Linking>, you can use `<ulink url="…">` instead.

**Comment by jstedfast** [comment]
Of course, now that the docs are fixed in gmime's source repo, I don't think they can be updated on developer-old.gnome.org anymore (I think that's been archived).

The docs used to get regenerated every release, but they don't anymore.
