### ISSUE TITLE
Manual link in README is broken

### ISSUE THREAD

**Issue by rafael2k** [jstedfast/gmime#135]
In this line:
"You can find online developer documentation at http://library.gnome.org/devel/gmime/stable/"
I get 404.

**Comment by jstedfast** [comment]
I'll probably try to use GitHub Pages or something.

**Comment by ojwb** [comment]
They seem to now be at https://developer-old.gnome.org/gmime/stable/

**Comment by jstedfast** [comment]
Looks like the link has already been updated in the README
