### ISSUE TITLE
No new releases via gnome.org?

### ISSUE THREAD

**Issue by c-alpha** [jstedfast/gmime#138]
I've just scratched my head why issue #115 was still biting be in my homebrew setup. It turns out that the [homebrew formula for gmime](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmime.rb) is referencing the latest stable gmime release on gnome.org, which is the two year old 3.2.7.

Before lobbying the homebrew maintainers to switch their gmime formula to this repo, it seemed called for getting the gmime author's view on where future releases should be expected?

**Comment by jstedfast** [comment]
I'll be making future releases here since I no longer seem to have access to the GNOME FTP server (they likely changed the way they do things for security or migrating off old infrastructure or something, but I didn't get the memo).

**Comment by c-alpha** [comment]
Thanks for your swift response! And just the info I needed.

**Comment by c-alpha** [comment]
@jstedfast, apologies for reopening this.

I'm chatting with the homebrew maintainers in https://github.com/orgs/Homebrew/discussions/4101, and they're asking for some official confirmation by the Gnome project to confirm the new repo location.

Do you see any options for having information on gnome.org point to your GH repo? Perhaps an announcement on the gmime-devel mailing list? As the archive of that list is available via gnome.org, it could perhaps count as an "official link"?

**Comment by jstedfast** [comment]
The mailing-list is no longer functional AFAIK. I got a notice about all GNOME mailing lists being shut down a few months ago.

**Comment by c-alpha** [comment]
**Many thanks for chiming into the homebrew discussion thread!**

Updating the sourceforge could be one option (provided you can still log in there).

Perhaps the best thing would be to get a pointer message up on https://gitlab.gnome.org/Archive/gmime ? Maybe you could contact [Carlos Soriano](https://wiki.gnome.org/CarlosSoriano) who is listed as admin among the [project's members](https://gitlab.gnome.org/Archive/gmime/-/project_members) on gitlab.gnome.org, and ask him to put it up there?

**Comment by c-alpha** [comment]
Job done, many thanks!!!
