### ISSUE TITLE
gmime 3.x release?

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#153]
i know there's a gmime 4.0 plan, but there are several bugfixes sitting in git that seem to apply to the 3.x series.  maybe it's time to make another gmime release in the 3.x series even if 4.0 isn't ready to ship?

**Comment by jstedfast** [comment]
Yea, it's probably time for a new 3.x release.

 I haven't even started on 4.0 yet (just don't have any free time anymore).

**Comment by jstedfast** [comment]
just released 3.2.14
