### ISSUE TITLE
new minor point release?

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#166]
it looks like there have been a couple significant changes since the last release:

- a fix for memory leaks
- a fix for infinite loops

maybe it's worth cutting a minor point release with these fixes?  or should i just import those patches in debian?

**Comment by jstedfast** [comment]
There's more fixes I want to do for the infinite loop fix since the output it produces is technically not correct (then again, what are the odds of a parameter *name* that exceeds the max line length?)

I just need to find enough time to work on it.

**Comment by dkg** [comment]
i don't much mind breaking the correctness of the output for a parameter name perverse enough to exceed the max length limit 😛

I'm more concerned about malicious mail being able to tickle gmime into an infinite loop.

**Comment by jstedfast** [comment]
Fair point. Just released 3.2.15
