### ISSUE TITLE
gpg encryption: --hidden-recipient

### ISSUE THREAD

**Issue by gauteh** [jstedfast/gmime#2]
Hi,

It would be great if we could have access to the `--hidden-recipient` (or `-R`) (https://www.gnupg.org/documentation/manuals/gnupg-devel/GPG-Key-related-Options.html) option when encrypting. Especially, when encrypting for `Bcc:` recipients this would be very useful. Otherwise it is very easy to see who all recipients are, with the option, it is only possible to see the number of recipients.

It would also be useful with an option to only hide `Bcc:` recipients.

> Note that `-R` replaces `-r`.

Are there any plans to move to gpgme or similar?

* https://mail.gnome.org/archives/gmime-devel-list/2017-February/msg00010.html
* https://lists.gnupg.org/pipermail/gnupg-devel/2017-February/032637.html

**Comment by jstedfast** [comment]
git master has already moved 100% to gpgme :)

I just need to figure out an API to allow the hidden recipient thing...

**Comment by gauteh** [comment]
Jeffrey Stedfast writes on februar 23, 2017 12:40:
> git master has already moved 100% to gpgme :)
> 
> I just need to figure out an API to allow the hidden recipient thing...

ah great!

**Comment by jstedfast** [comment]
Looks like this idea got shot down on the gnupg-devel list...

**Comment by gauteh** [comment]
Jeffrey Stedfast writes on mars 22, 2017 17:24:
> Looks like this idea got shot down on the gnupg-devel list...

Yeah, too bad - I think this would be a very useful feature. Was
'--throw-keyids' also rejected?

**Comment by jstedfast** [comment]
I think Werner said something about thinking about that one as he could see some uses for that and it wouldn't be as hard to implement.

**Comment by gauteh** [comment]
Jeffrey Stedfast writes on mars 22, 2017 22:24:
> I think Werner said something about thinking about that one as he could see some uses for that and it wouldn't be as hard to implement.
 
Ok, it should have more or less the same effect. A regular receiver
will know anyway that there are a number of hidden keys and that there
likely is Bcc receivers.

**Comment by muelli** [comment]
FWIW: I think the new 1.9.0 release includes a flag:
https://www.gnupg.org/documentation/manuals/gpgme/Encrypting-a-Plaintext.html#Encrypting-a-Plaintext
>      
> GPGME_ENCRYPT_THROW_KEYIDS
> 
> The GPGME_ENCRYPT_THROW_KEYIDS symbols requests that the identifiers for the decrption keys are not included in the ciphertext. On the receiving side, the use of this flag may slow down the decryption process because all available secret keys must be tried. This flag is only honored for OpenPGP encryption.
>

**Comment by gauteh** [comment]
muelli writes on mars 29, 2017 14:55:
> FWIW: I think the new 1.9.0 release includes a flag:
> https://www.gnupg.org/documentation/manuals/gpgme/Encrypting-a-Plaintext.html#Encrypting-a-Plaintext
>>      
>> GPGME_ENCRYPT_THROW_KEYIDS
>> 
>> The GPGME_ENCRYPT_THROW_KEYIDS symbols requests that the identifiers for the decrption keys are not included in the ciphertext. On the receiving side, the use of this flag may slow down the decryption process because all available secret keys must be tried. This flag is only honored for OpenPGP encryption.
>> 

Excellent! I would use this flag only for composing e-mails containing Bcc
receivers. If it could be specified to the GMime interface that would
solve my issue.

**Comment by jstedfast** [comment]
Implemented :)

**Comment by gauteh** [comment]
Jeffrey Stedfast writes on mars 29, 2017 15:11:
> Implemented :)

Woha! Nice!
