### ISSUE TITLE
New line issue with GMimeMessagePart

### ISSUE THREAD

**Issue by thom-jenks** [jstedfast/gmime#23]
When parsing an existing message containing a message/rfc822 part, an extra new line is inserted above the sub-message headers on writing the GMimeObject to stream:

For example:

```
--------------BE59E1D6AC7C8CA44EB57E2E
Content-Type: message/rfc822;
 name="AttachedMessage.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename="AttachedMessage.eml"
                                        <---- Multiple new lines here

X-Account-Key: account1
X-Mozilla-Keys:
[... AttachedMessage.eml headers continue ...]                                           
```

instead of 

```
--------------BE59E1D6AC7C8CA44EB57E2E
Content-Type: message/rfc822;
 name="AttachedMessage.eml"
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename="AttachedMessage.eml"

X-Account-Key: account1
X-Mozilla-Keys:
[... AttachedMessage.eml headers continue ...]                                           
```

This causes the raw source to the rendered by many email clients (tested - Outlook, Thunderbird, MacOS Mail)

**Comment by thom-jenks** [comment]
Upon superficial experimentation, this seems somewhat related to the changes made in 29a0beffa392d993de8b06fc9dd57baa858a4793

**Comment by jstedfast** [comment]
My instinct would be that it had something to do with writing out the message->marker line in gmime-message-part.c (just took a quick look at the code tho and didn't see anything obviously wrong with the logic).

Short of that, my next inclination would be to suspect the code that writes a blank line after the headers (also in gmime-message-part.c). I'd have to check the other GMimeObject implementations to see if they also write a blank line after writing the headers and/or check if writing the headers already included the blank line (I don't recall off the top of my head).

I don't see anything obviously wrong with the logic in the commit you linked to.

If you do some more digging, let me know what you find. I probably won't have time to look at this tonight.

**Comment by thom-jenks** [comment]
I don't think there is anything wrong with the logic but applying a similar approach to the '*_write_to_stream' functions by adding a newline filter seemed to do the job. At the same time, I don't really know the library well enough to know if that is the correct approach for MessagePart.

I'll have a look into some of those those things this evening and let you know what I find!

**Comment by jstedfast** [comment]
Ah, ok... maybe a bug in the dos2unix or unix2dos filter (which one are you using? will depend on the platform)

**Comment by thom-jenks** [comment]
Ah, I haven't explained myself well. By editing the write_to_stream functions within gmime-message-part.c such that they write to a filtered stream in a similar way to gmime-message.c in the referenced commit I was able to 'fix' things.

**Comment by jstedfast** [comment]
You shouldn't need to do that since `g_mime_header_list_write_to_stream()` already creates a newline filter and uses it.

The reason that `gmime-message.c:write_headers_to_stream()` does that is because it doesn't call `g_mime_header_list_write_to_stream()`. It more-or-less duplicates the logic of that function because it needs to merge the `message` headers and the `mime_part` headers.

**Comment by thom-jenks** [comment]
Right. I have done some digging:

When writing the message part, after g_mime_header_list_write_to_stream, the tail of the stream is `<final header name>: <header value>\NL'` where `\NL` is the new line sequence.

You then explicitly write a newline immediately

(`<final header name>: <header value>\NL\NL`)

and then you write what message->marker is pointing to. For me this happened to be a single new line character `\n`.

Only then is the GMimeMessage* written to the stream. I don't really understand the specifics of message->marker but removing either of the `...write_string(new_line)` or the `if (message->marker...)` blocks fixed this for me. 

Many thanks for your assistance by the way - it's much appreciated.

**Comment by jstedfast** [comment]
No problem - always glad to help people who start trying to dig into bugs themselves, it helps save me a lot of time :)

What you've found suggests that the parser is probably buggy in its logic deciding if there is a marker or not. I'll have to look at that and see if I can figure that out.

Where are you getting the original message? Is it being parsed as a message/rfc822 part's content? Or are you parsing it from a stream and adding it to a GMimeMessagePart and then writing it out?

Just trying to figure out the code flow which might make it easier to figure out.

**Comment by thom-jenks** [comment]
Ah, if that's the case - I've got no chance of fixing this myself!

I have generated a test email with a message attachment from my mail client which I read in (similar to the basic_example.c example) which I am then writing out. I'm not building the message from scratch.

**Comment by thom-jenks** [comment]
Here is the test that I was using:

https://pastebin.com/ftmg0VCx

**Comment by jstedfast** [comment]
Ok, I can reproduce the problem... it only seems to happen if the source message is in DOS format (i.e. `<CR><LF>` line endings).

**Comment by jstedfast** [comment]
Fixed.

Thanks for reporting this bug and for all of the work you did to try and narrow down the problem, it was very much appreciated :)
