### ISSUE TITLE
warnings from zentimer.h in tests/test-parser.c

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#25]
Trying to compile `tests/test-parser.o` results in the following warnings:

```
  CC     test-parser.o
In file included from test-parser.c:38:0:
../zentimer.h:121:1: warning: ‘ZenTimerResume’ defined but not used [-Wunused-function]
 ZenTimerResume (ztimer_t *ztimer)
 ^~~~~~~~~~~~~~
../zentimer.h:112:1: warning: ‘ZenTimerPause’ defined but not used [-Wunused-function]
 ZenTimerPause (ztimer_t *ztimer)
 ^~~~~~~~~~~~~
```

I don't understand enough about zentimer to know how to avoid this warning, but if it's not a real problem, we should find a way to suppress the warning so that useful warnings are not obscured by the noise.

**Comment by jstedfast** [comment]
Yea, I get the same. I'll try to look into this.

**Comment by jstedfast** [comment]
I've disabled the zentimer in test-parser.c for now, there's no way to silence those warnings any other way without making more fine-grained defines for enabling functionality in it (and it's just not worth it I don't think).
