### ISSUE TITLE
PGP/MIME tests currently failing

### ISSUE THREAD

**Issue by bremner** [jstedfast/gmime#3]
Maybe this is known but it looks like test-pgp and pest pgp-pgpmime need updating
<pre>
 (process:4069): gmime-CRITICAL **: g_mime_crypto_context_set_request_password: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4069): gmime-CRITICAL **: g_mime_crypto_context_import_keys: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4069): gmime-CRITICAL **: g_mime_crypto_context_import_keys: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4069): gmime-CRITICAL **: g_mime_crypto_context_export_keys: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed
/bin/bash: line 4:  4069 Segmentation fault      ./${test} -v ${testdir}

(process:4094): gmime-CRITICAL **: g_mime_crypto_context_set_request_password: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4094): gmime-CRITICAL **: g_mime_crypto_context_import_keys: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4094): gmime-CRITICAL **: g_mime_crypto_context_import_keys: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4094): gmime-CRITICAL **: g_mime_multipart_signed_sign: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4094): gmime-CRITICAL **: g_mime_message_set_mime_part: assertion 'GMIME_IS_OBJECT (mime_part)' failed

(process:4094): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(process:4094): gmime-CRITICAL **: g_mime_multipart_encrypted_encrypt: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4094): gmime-CRITICAL **: g_mime_message_set_mime_part: assertion 'GMIME_IS_OBJECT (mime_part)' failed

(process:4094): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(process:4094): gmime-CRITICAL **: g_mime_multipart_encrypted_encrypt: assertion 'GMIME_IS_CRYPTO_CONTEXT (ctx)' failed

(process:4094): gmime-CRITICAL **: g_mime_message_set_mime_part: assertion 'GMIME_IS_OBJECT (mime_part)' failed

(process:4094): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(process:4094): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Testing PGP/MIME implementation: failed (3 errors, 0 warnings)
Results: 7 tests passed; 2 tests failed.
Failed tests: 
 test-pgp
 test-pgpmime
Makefile:961: recipe for target 'check-local' failed
make[3]: *** [check-local] Error 255
</pre>

**Comment by jstedfast** [comment]
You don't have crypto support enabled in your build, that's why.

**Comment by bremner** [comment]
Jeffrey Stedfast <notifications@github.com> writes:

> You don't have crypto support enabled in your build, that's why.
>
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jstedfast/gmime/issues/3#issuecomment-286399616

Hmm. OK, what am I missing? Here's the output from configure.

Configuration:

  Source code location: .
  Install prefix:       /usr/local
  Compiler:             gcc

  Profiling enabled:    no
  Coverage enabled:     no

  Large file support:   yes
  Console warnings:     no
  PGP/MIME support:     yes
  S/MIME support:       yes

  Vala bindings:        no

**Comment by bremner** [comment]
David Bremner <david@tethera.net> writes:

> Jeffrey Stedfast <notifications@github.com> writes:
>
>> You don't have crypto support enabled in your build, that's why.
>>
>>
>> -- 
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/jstedfast/gmime/issues/3#issuecomment-286399616
>
> Hmm. OK, what am I missing? Here's the output from configure.
>
> Configuration:
>
>   Source code location: .
>   Install prefix:       /usr/local
>   Compiler:             gcc
>
>   Profiling enabled:    no
>   Coverage enabled:     no
>
>   Large file support:   yes
>   Console warnings:     no
>   PGP/MIME support:     yes
>   S/MIME support:       yes
>
>   Vala bindings:        no

Oh, I got it. I was missing libgpgme-dev when I ran autogen.sh, so I
guess I got the old non-GPGME crypto support. You're correct the tests
are fine after distclean and re-autogen.sh.

d
