### ISSUE TITLE
Fix '-Wstrict-prototypes' compile warning

### ISSUE THREAD

**Issue by albrechtd** [jstedfast/gmime#33]
Building applications using gmime with the gcc/clang compiler flag '-Wstrict-prototypes' produces a warning in the header file gmime-autocrypt.h.  Trivial fix:

<pre>--- a/gmime/gmime-autocrypt.h
+++ b/gmime/gmime-autocrypt.h
@@ -133,7 +133,7 @@ struct _GMimeAutocryptHeaderListClass {
 
 GType g_mime_autocrypt_header_list_get_type (void);
 
-GMimeAutocryptHeaderList *g_mime_autocrypt_header_list_new ();
+GMimeAutocryptHeaderList *g_mime_autocrypt_header_list_new (void);
 guint g_mime_autocrypt_header_list_add_missing_addresses (GMimeAutocryptHeaderList *ahl, InternetAddressList *list);
 void g_mime_autocrypt_header_list_add (GMimeAutocryptHeaderList *ahl, GMimeAutocryptHeader *ah);
 
</pre>

BTW, it might be a good idea to add this warning option to gmime's compiler flags…

**Comment by jstedfast** [comment]
Thanks. I tried adding -Wstrict-prototypes but that causes warnings with examples/ due to getopt.h's definition of getopt().

Will test on Linux later (only tested on Mac so far).

**Comment by albrechtd** [comment]
>  causes warnings with examples/ due to getopt.h's definition of getopt()

Hmmm, just use GOptionContext (you link against libglib anyway) instead of getopt?

**Comment by jstedfast** [comment]
done
