### ISSUE TITLE
Missing INSTALL file, duplicate repos

### ISSUE THREAD

**Issue by sanmai-NL** [jstedfast/gmime#39]
The `INSTALL` file is mentioned in the `README` but missing.

Also, could you clarify which repo URL is authoritative; this one or https://github.com/GNOME/gmime/?

**Comment by jstedfast** [comment]
The INSTALL file is auto-generated by `./autogen.sh`

This is the official repo.

**Comment by sanmai-NL** [comment]
Can you please add that important info to the `README` then? Keep in mind, how can a user tell he or she should run `./autogen.sh`? Not everyone knows or looks for `autotools` scripts.

**Comment by jstedfast** [comment]
This is how all GNOME libraries work. It's how all GNU packages work as well. The sources on git are not the same sources distributed via tarball.

Adding stuff to a README for git would just confuse people building from a tarball because there is no autogen.sh script.
