### ISSUE TITLE
Please switch to libidn2

### ISSUE THREAD

**Issue by elkrejzi** [jstedfast/gmime#48]
Software is being ported to libidn2 to support IDNA2008. The goal is to replace libidn with libidn2, but to do that, nothing should depend on libidn anymore. This package still uses old libidn, so please port it to libidn2.

See also:

https://libidn.gitlab.io/libidn2/manual/libidn2.html#Converting-from-libidn
https://fedoraproject.org/wiki/Changes/IDNA2008

**Comment by jstedfast** [comment]
Thanks for the notice! I didn't even realize I was using an old version of the library.

I plan to make a new release soon (I've got an Efail work-around I want to publish, just waiting to get some feedback on it)
