### ISSUE TITLE
Duplicate header name when generating msgs

### ISSUE THREAD

**Issue by zh-jq** [jstedfast/gmime#5]
Hello, when porting code to gmime 3.0, I found that msg generated become:
`From: =?gb2312?b?wO7LxA==?= <aaa@example.com>`
`To: =?gb2312?b?1cXI/Q==?= <bbb@example.com>`
`Subject:Subject: =?GBK?B?suLK1NPKvP4=?=`
`Date:Date: Sat, 06 May 2017 20:24:22 +0800`
`MIME-Version:MIME-Version: 1.0`
Gmime version: 3.0.0+dfsg1-1 in Debian experimental.

**Comment by jstedfast** [comment]
Thanks! Just fixed that with this commit https://github.com/jstedfast/gmime/commit/905c493cbd529451bf23e6d5f6164878505c701a
