### ISSUE TITLE
handle message/global (like message/rfc822)

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#50]
Internationalized e-mail headers cause some level of confusion, but `message/global` looks like it is basically `message/rfc822` but not necessarily 7-bit clean, and textual headers are expected to be utf-8 encoded.

it would be nice if gmime could handle this as smoothly as it handles `message/rfc822`.

See [RFC 6532](https://tools.ietf.org/html/rfc6532) for more details.

**Comment by jstedfast** [comment]
Ah, thanks - easy fix :)

**Comment by jstedfast** [comment]
Just released GMime 3.2.1 with this fix along with a number of other fixes. Has it really been nearly a year since I last made a release!? Holy cow!
