### ISSUE TITLE
Reintroduced message headers

### ISSUE THREAD

**Issue by albrechtd** [jstedfast/gmime#51]
[RFC 5322, Sect. 3.6.6](https://tools.ietf.org/html/rfc5322#section-3.6.6) defines _Resent-*_ headers which can be used when a message is reintroduced (not forwarded!) into the transport infrastructure.  Although it is possible to access them using gmime's generic header access methods, it would be very helpful if they could be read or written by the more specialised methods like g_mime_message_get_addresses() etc.

Note 1: According to the RFC, a new set of resent fields is prepended to the message for each reintorduction.  I.e. a header like Resent-From: may occur multiple times, unlike From:.
Note 2: This feature seems to be used rarely.

**Comment by jstedfast** [comment]
Yea, this is something that I've had in MimeKit for a while and figured I should add to GMime, but no one had asked for it until now... :p

**Comment by albrechtd** [comment]
Thanks a lot, I'll look into it…

**Comment by albrechtd** [comment]
Please let me add a few remarks about your implementation…
It appears as if the implementation assumes that there is exactly _one_ set of Resent-* headers.  However, RFC5322 states

> Resent fields SHOULD be added to any message that is reintroduced by a user into the transport system.  A separate set of resent fields SHOULD be added each time this is done.  All of the resent fields corresponding to a particular resending of the message SHOULD be grouped together.  Each new set of resent fields is prepended to the message; that is, the most recent set of resent fields appears earlier in the message.

I must admit that I have only _one_ message in my mailboxes with two sets of Resent-* headers (plus a low percentage of messages with one set), but to me it looks as if your implementation does not comply with the RFC.  E.g. run the attached test-resent-in.c (actually containing a stripped-down version of the message with two Resent-* sets).  The output is

```
** Message: 21:04:24.408: From: addresses
** Message: 21:04:24.408: 0: 'Orig Sender 1 <orig_sender1@some.org>'
** Message: 21:04:24.408: 1: 'Orig Sender 2 <orig_sender2@some.org>'
** Message: 21:04:24.408: Sender: addresses
** Message: 21:04:24.408: 0: 'real_sender@some.org'
** Message: 21:04:24.408: Resent-From: addresses - which block?
** Message: 21:04:24.408: 0: 'Orig Sender 1r2 <orig_sender1@some.org>'
** Message: 21:04:24.408: 1: 'Orig Sender 2r2 <orig_sender2@some.org>'
** Message: 21:04:24.408: 2: 'Orig Sender 1r1 <orig_sender1@some.org>'
** Message: 21:04:24.408: 3: 'Orig Sender 2r1 <orig_sender2@some.org>'
** Message: 21:04:24.408: Resent-Sender: addresses - which block?
** Message: 21:04:24.408: 0: 'Resend Daemon 2 <resent_2@some.org>'
** Message: 21:04:24.408: 1: 'Resend Daemon 1 <resent_1@some.org>'
````

Likewise, adding resent headers multiple times (test-resent-out.c) does not produce multiple headers, and they are not prepended as required.

I must admit, though, that I have no immediate idea for a simple solution (maybe define Resent-* headers as a GList or GPtrArray of items?).

Two other points:
- methods for reading/writing the (groups elements) Resent-Date: and Resent-Message-ID: would be helpful
- Resent-Reply-To: is not defined by RFC5322 (and I wonder if it makes any sense).
[testcases.zip](https://github.com/jstedfast/gmime/files/2611657/testcases.zip)

**Comment by jstedfast** [comment]
I added it because older versions of the spec had it (from rfc5322):

```
   obs-resent-rply =   "Resent-Reply-To" *WSP ":" address-list CRLF

   As with other resent fields, the "Resent-Reply-To:" field is to be
   treated as trace information only.
```

Anyway, to group them, etc, makes for a far more complicated API for a very infrequently used feature :-\

In other words, it would be impossible to do it using the g_mime_message_get_addresses() API or like the similar g_mime_message_get_from/to/cc/bcc() functions like I implemented for the equivalent resent headers (which is what I thought you wanted based on your original comment).

I can add APIs for the resent-date/message-id, but let's first figure out what the API for resent stuff should look like.

Is this for Balsa's use? or for something else?

**Comment by albrechtd** [comment]
> I added it because older versions of the spec had it (from rfc5322):

Yes, you're right – I forgot the obsolete stuff.  Sorry for the noise…

> Anyway, to group them, etc, makes for a far more complicated API for a very infrequently used feature :-\

I agree.  But you should add a remark in the docs that albeit the api is perfect for 99.999something % of cases, it's _not_ struictly RFC-compliant IMHO.

> Is this for Balsa's use? or for something else?

No, not for Balsa, but for a project investigating the statistical properties of message envelopes if anomalities might indicate spam or attacks.  Actually, I stumbled on some malspam messages with Resent headers.  But I'm not sure if this a promising approach, more like a shot in the dark (or “AI”, if you like buzzword bingo).

**Comment by jstedfast** [comment]
I got to thinking more about this last night and the more I thought about it, the more frustrated I got with how poorly designed the whole Resent-* header idea is.

Consider this:

```
Resent-From: addr
Resent-To: addr
Resent-Message-Id: msgid
Resent-Date: date
Resent-Sender: addr
Resent-Cc: addr
Resent-To: addr
Resent-From: addr
Resent-Message-Id: msgid
Resent-Date: date
```

How do you find where the first group of Resent-* headers ends and the second group begins?

It's impossible.

Now, in *practice* the groups would likely be separated by at least some Received headers (assuming the transport was SMTP), but who really knows.

I think that ultimately, the only real way of handling this is to request the raw headers from GMime (using the GMimeHeaderList API).

My guess is you're already doing that but having to then do internet_address_list_parse() etc on the raw header values is just boiler plate code you were hoping to avoid and have nicer convenient API's for access that w/o the need to deal with parsing.

Maybe it's time to share my long-term dream idea for GMime (and MimeKit tbh).

Right now, GMime has `GMimeHeaderList` and the list contains a list of `GMimeHeader` items.

What if, ultimately, I added subclasses of `GMimeHeader`?

Here are the ones I think would be useful:

`GMimeAddressHeader`: for things like Sender/From/To/Cc/Bcc and the Resent-* variants of those
`GMimeReceivedHeader`: for Received headers

Other ideas that might be useful but I'm not as strong about:

`GMimeReferencesHeader`: for References (and maybe In-Reply-To?)
`GMimeMessageIdHeader`: for Message-Id and Resent-Message-Id ... (or maybe this is what In-Reply-To should use?)
`GMimeDateHeader`: for Date and Resent-Date
`GMimeDkimSignatureHeader`: for DKIM-Signature - right now GMime doesn't implement support for this, but I did add it to MimeKit and at some point it might be nice to add it here as well. It was just painful so I'm not excited about doing the work :(
`GMimeAutocrypt*Header`: For the Autocrypt headers that @dkg added support for.

This is what I'm calling my "4.0" plan.

Anyway, I think this solution would be the way to provide the Resent-* convenience API's that you want in a way that actually makes it useful.

What do you think?

In the meantime, I can add the g_mime_message_get_resent_date/message_id() API's that mimic the existing get_date/message_id() APIs even though they aren't a perfect solution for Resent-* behavior.

**Comment by albrechtd** [comment]
I think your “4.0” plan is a cool idea; I like the idea of header sub-classing! 

But for sure it's nothing which is urgent.  And, yes, for my investigation (I actually have no idea yet whether it will lead to any insight or not; in the latter case I would probably simply ignore those headers), I implemented the header evaluation myself.

And if nobody asked for explicit Resent-* header support before, the likelihood is low that it will be needed in the future…

Thanks a lot for your time and thoughts, Albrecht.
