### ISSUE TITLE
vala build issue

### ISSUE THREAD

**Issue by bdubbs** [jstedfast/gmime#53]
The NEWS file for version 3.2.2 says: Fixed packaging to include Vala files.

But evidently it is not complete.  During build, I get:

  GICOMP   GMime-3.0.gir
make[3]: *** No rule to make target 'GMime-3.0.metadata', needed by 'gmime-3.0.vapi'.  Stop

I can build successfully with --enable-vala=no

  -- Bruce Dubbs
     linuxfromscratch.org

**Comment by jstedfast** [comment]
Yea, I know :-\

I didn't have some package or another installed on my local system that built the GMime-3.0.metadata file when I rolled that tarball, but I do now, so the next release will fix that.

Thanks.
