### ISSUE TITLE
Unlikely NULL-pointer dereference

### ISSUE THREAD

**Issue by albrechtd** [jstedfast/gmime#56]
The latest [cppcheck](http://cppcheck.net/) v. 1.85 detetcs a (rather unlikely) NULL pointer dereference in g_mime_references_parse(), which can be trivially fixed by just shifting the initialisation of the local var `inptr` as in the attached diff.

Note that cppcheck also reports a possible null pointer dereference for html_tag in fuction enriched_to_html() which is actually a false-positive.  It could be avoided by changing line 497 to
`if (html_tag != NULL) {`
which _should_ (I think…) be logically equivalent.
[gmime-references-NULL-ptr-deref.zip](https://github.com/jstedfast/gmime/files/2673404/gmime-references-NULL-ptr-deref.zip)

**Comment by jstedfast** [comment]
For g_mime_references_parse(), technically that's protected by the g_return statement that checks text != NULL (at least if the g_return stuff is enabled). I'm ok with making the change, though.

As far as the enriched_to_html() case goes, let's make that change for sure. That makes the code clearer anyway, I think.

**Comment by albrechtd** [comment]
> For g_mime_references_parse(), technically that's protected by the g_return statement that checks text != NULL (at least if the g_return stuff is enabled). I'm ok with making the change, though.

Ouch.  You're right, of course, this is  a false positive, too.  Sorry for the noise…

**Comment by jstedfast** [comment]
No problem. I made the enriched_to_html() change because I felt that was an improvement in code clarity even for us humans. I'm not sure about the other warning, though. I think I'll pass for now.

FWIW, I don't mind these types of fixes, especially if making the warning go away also improves code clarity.
