### ISSUE TITLE
Migrate Back to GNOME Infra?

### ISSUE THREAD

**Issue by BrainBlasted** [jstedfast/gmime#57]
gmime has a duplicate repo on GNOME infrastructure with no indication that the project's been moved to GitHub. Since we now use GitLab for GNOME and GMime is used in GNOME projects, it would be nice to have on GNOME infrastructure again.

**Comment by jstedfast** [comment]
I don't have commit access to the GNOME gitlab.

I also would rather stick with GitHub since that's where all of my other projects are.
