### ISSUE TITLE
RFC2047 format_options encoding mode doesn't work as expected

### ISSUE THREAD

**Issue by zh-jq** [jstedfast/gmime#6]
Hello, it's really helpful with the new param encoding mode format options.
But I have tested both RFC2047 and RFC2231 encoding mode.
The result is always
`Content-Disposition: attachment; name*=gb2312''%C3%FB%B3%C6%D7%D6%B6%CE`
It seems RFC2047 option doesn't work.
Gmime version: 3.0.0+dfsg1-1 in Debian experimental

**Comment by jstedfast** [comment]
how are you setting it?

**Comment by zh-jq** [comment]
I get a new format option, and use g_mime_format_options_set_param_encoding_method() set RFC2047,
then use that format option in g_mime_object_to_string()

**Comment by zh-jq** [comment]
Exampe code:
```
#include <stdlib.h>
#include <stdio.h>
#include <gmime/gmime.h>

int main(int argc, char *argv[])
{
        g_mime_init();

        GMimeTextPart *part = g_mime_text_part_new();
        g_mime_object_set_content_type_parameter((GMimeObject *)part, "name", "名字");

        GMimeFormatOptions *ops = g_mime_format_options_new();
        g_mime_format_options_set_param_encoding_method(ops, GMIME_PARAM_ENCODING_METHOD_RFC2047);
        char *str = g_mime_object_to_string((GMimeObject *)part, ops);

        fprintf(stdout, "Msg:\n%s", str);

        free(str);
        g_mime_format_options_free(ops);
        g_object_unref(part);

        g_mime_shutdown();
        return 0;
}
```
DId I miss something?

**Comment by zh-jq** [comment]
The only function that handle RFC2047 is g_mime_param_list_encode:gmime-param.c, which is called in
```
gmime-content-type.c:   g_mime_param_list_encode (content_type->params, options, TRUE, str);
gmime-disposition.c:    g_mime_param_list_encode (disposition->params, options, TRUE, str);
gmime-header.c: g_mime_param_list_encode (disposition->params, options, TRUE, str);
gmime-header.c: g_mime_param_list_encode (content_type->params, options, TRUE, str);
```
The two call in gmime-header.c is used in formatters[], which is called in function g_mime_header_new(), and options is set to NULL:
```
	if (!raw_value && value)
		header->raw_value = formatter (header, NULL, header->value, charset);
```
The call in gmime-content-type.c and gmime-disposition.c is similar, in functions named like g_mime_content_type/disposition_encode(), and these functions is called in gmime-object.c when
changing content-type/content-disposition:
```
raw_value = g_mime_content_type_encode (content_type, NULL);
raw_value = g_mime_content_disposition_encode (disposition, NULL);
```
Options are set to NULL to here.

So, actually, the RFC2047 param encoding options is not used anywhere.

The solution may be add GmimeFormatOptions params in functions that change Content-Type/Content-Disposition in gmime-object.c.
