### ISSUE TITLE
some memory leak 

### ISSUE THREAD

**Issue by xspeed1989** [jstedfast/gmime#61]
int main()
{
	CURL *pCurl = curl_easy_init();
	curl_easy_setopt(pCurl, CURLOPT_URL, "imaps://imap.qq.com/INBOX;MAILINDEX=1");
	curl_easy_setopt(pCurl, CURLOPT_USERNAME, "xxxx");
	curl_easy_setopt(pCurl, CURLOPT_PASSWORD, PWD);
	curl_easy_setopt(pCurl, CURLOPT_WRITEFUNCTION, write_callback);
	curl_easy_setopt(pCurl, CURLOPT_SSL_VERIFYHOST, 0);
	curl_easy_setopt(pCurl, CURLOPT_SSL_VERIFYPEER, 0);
	//curl_easy_setopt(pCurl, CURLOPT_CUSTOMREQUEST, "CAPABILITY");
	std::string str;
	curl_easy_setopt(pCurl, CURLOPT_WRITEDATA, &str);
	CURLcode res = curl_easy_perform(pCurl);

	
	g_mime_init();
	while (true)
	{
	
		/* load a GMimeMessage from a stream */
		GMimeMessage *message;
		GMimeStream *stream;
		GMimeParser *parser;
		GByteArray array;
		array.data = (guint8 *)&str[0];
		array.len = str.length();
		stream = g_mime_stream_mem_new_with_byte_array(&array);
		parser = g_mime_parser_new_with_stream(stream);
		g_object_unref(stream);
		message = g_mime_parser_construct_message(parser, NULL);
		g_object_unref(parser);
		//g_mime_message_foreach(message, GMimeObjectForeachCallback, nullptr);
	}
	g_mime_shutdown();
		
}

the memory will increase always!

**Comment by jstedfast** [comment]
That's not the way you are supposed to use GByteArray. You are supposed to alloc it using g_byte_array_new().

That's probably causing your problems.

ALso you should g_object_unref the message as well.
