### ISSUE TITLE
How to get GMimeReferences from GMimeMessage?

### ISSUE THREAD

**Issue by Jeevhi** [jstedfast/gmime#92]
I am trying to get message ids from reference and in-reply-to field. I see that GMimeReferences  is define but there is no function to get it from parsed message. Can you help. 

Thanks

**Comment by jstedfast** [comment]
You need to use: `GMimeReferences *g_mime_references_parse (GMimeParserOptions *options, const char *text);`

```c
GMimeReferences *references;
const char *value;

value = g_mime_object_get_header (GMIME_OBJECT (message), "References");
references = g_mime_references_parse (NULL, value);
```

**Comment by Jeevhi** [comment]
Thank you for quick response. Does GMimeReferences needs to be freed after use?

**Comment by jstedfast** [comment]
Yes.
