### ISSUE TITLE
Infinite loop on gir file

### ISSUE THREAD

**Issue by oddodaoddo** [jstedfast/gmime#99]
master branch, slackware 14.2 linux system

After autogen.sh I run make and it runs fine until it goes into an infinite loop printing out this line:

GMime-3.0.gir:25533.1-25533.0: warning: expected end element of `type'

**Comment by jstedfast** [comment]
Sorry for taking so long to respond. I'm not very knowledgeable about gir files or the Vala compiler stuff so I'm not sure how to fix this (I didn't seem to have any issues when I was working on GMime more frequently - now I'm on Windows and can't check this)

**Comment by jstedfast** [comment]
WORKSFORME
